export { default as Header } from "./header/header";
export { default as Intro } from "./intro/intro";
export { default as Services } from "./services";
export { default as Logo } from "./logo/logo";
export { default as Statistic } from "./statistic";
export { default as About } from "./about";
export { default as Projects } from "./projects";
export { default as FeedBacks } from "./feedBacks";
export { default as Footer } from "./footer";
