import svgs from "@/public/svgs";
import Image from "next/image";
import Link from "next/link";
import React from "react";

type ProjectDetailProps = {
  params: {
    projectId: string;
  };
};

export const metadata = {
  title: "Craft.me | Project",
  description: "Generated by create next app",
};

const ProjectDetail = ({ params }: ProjectDetailProps) => {
  const { projectId } = params;
  return (
    <section className="bg-blue min-h-screen w-full flex flex-col gap-4 items-center justify-center">
      <Image width={500} height={500} src={svgs.notFound} alt="not-found" />
      <h1 className="text-3xl text-sea">Resource not found.</h1>

      <Link
        href="/"
        className="border-sea border py-4 px-8 rounded-full text-sea font-semibold hover:bg-mountain hover:border-mountain hover:text-white transition"
      >
        Go back home
      </Link>
    </section>
  );
};

export default ProjectDetail;
